sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t arunakatugampolaig/docker-alpine-openjdk-snappy .

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push arunakatugampolaig/docker-alpine-openjdk-snappy